__correct_traceid_dict__={
    'CL.AGE  00..E'  : 'CL.AGE.00.EHE',
    'CL.AGE  00..N'  : 'CL.AGE.00.EHN',
    'CL.AGE  00..Z'  : 'CL.AGE.00.EHZ',
    '.AGE..EHZ'      : 'CL.AGE.00.EHZ',
    '.AGE..EHN'      : 'CL.AGE.00.EHN',
    '.AGE..EHE'      : 'CL.AGE.00.EHE',
    'crlnet.AGE..Z'  : 'CL.AGE.00.EHZ',
    'crlnet.AGE..N'  : 'CL.AGE.00.EHN',
    'crlnet.AGE..E'  : 'CL.AGE.00.EHE',
    'CL.AGE.01.EHE'  : 'CL.AGE.00.EHE',
    'CL.AGE.01.EHN'  : 'CL.AGE.00.EHN',
    'CL.AGE.01.EHZ'  : 'CL.AGE.00.EHZ',
    'CL.AGEO.--.EHE' : 'CL.AGEO.00.EHE',
    'CL.AGEO.--.EHN' : 'CL.AGEO.00.EHN',
    'CL.AGEO.--.EHZ' : 'CL.AGEO.00.EHZ',
    'crlnet.AGEO..E' : 'CL.AGEO.00.EHE',
    'crlnet.AGEO..N' : 'CL.AGEO.00.EHN',
    'crlnet.AGEO..Z' : 'CL.AGEO.00.EHZ',
    'CL.AGEO.00.BHE'  : 'CL.AGEO.00.EHE',
    'CL.AGEO.00.BHN'  : 'CL.AGEO.00.EHN',
    'CL.AGEO.00.BHZ'  : 'CL.AGEO.00.EHZ',
    'CL.TRZ  00..Z'  : 'CL.TRZ.00.EHZ',
    'CL.TRZ  00..N'  : 'CL.TRZ.00.EHN',
    'CL.TRZ  00..E'  : 'CL.TRZ.00.EHE',
    'crlnet.TRZ..Z'  : 'CL.TRZ.00.EHZ',
    'crlnet.TRZ..N'  : 'CL.TRZ.00.EHN',
    'crlnet.TRZ..E'  : 'CL.TRZ.00.EHE',
    'CL.AIO  00..E'  : 'CL.AIO.00.EHE',
    'CL.AIO  00..N'  : 'CL.AIO.00.EHN',
    'CL.AIO  00..Z'  : 'CL.AIO.00.EHZ',
    'CL.AIO.--.EHE'  : 'CL.AIOA.00.EHE',
    'CL.AIO.--.EHN'  : 'CL.AIOA.00.EHN',
    'CL.AIO.--.EHZ'  : 'CL.AIOA.00.EHZ',
    'CL.AIOA.--.EHE' : 'CL.AIOA.00.EHE',
    'CL.AIOA.--.EHN' : 'CL.AIOA.00.EHN',
    'CL.AIOA.--.EHZ' : 'CL.AIOA.00.EHZ',
    'crlnet.AIOA..E' : 'CL.AIOA.00.EHE',
    'crlnet.AIOA..N' : 'CL.AIOA.00.EHN',
    'crlnet.AIOA..Z' : 'CL.AIOA.00.EHZ',
    'crlnet.AIO..E'  : 'CL.AIOA.00.EHE',
    'crlnet.AIO..N'  : 'CL.AIOA.00.EHN',
    'crlnet.AIO..Z'  : 'CL.AIOA.00.EHZ',
    'CL.AIOA.00.BHE'  : 'CL.AIOA.00.EHE',
    'CL.AIOA.00.BHN'  : 'CL.AIOA.00.EHN',
    'CL.AIOA.00.BHZ'  : 'CL.AIOA.00.EHZ',
    '.AIO..EHZ'      : 'CL.AIO.00.EHZ',
    '.AIO..EHN'      : 'CL.AIO.00.EHN',
    '.AIO..EHE'      : 'CL.AIO.00.EHE',
    'CL.ALI  00..E'  : 'CL.ALI.00.EHE',
    'CL.ALI  00..N'  : 'CL.ALI.00.EHN',
    'CL.ALI  00..Z'  : 'CL.ALI.00.EHZ',
    'CL.ALI.00.EHZ'  : 'CL.ALI.00.EHZ',
    'CL.ALI.00.EHN'  : 'CL.ALI.00.EHN',
    'CL.ALI.00.EHE'  : 'CL.ALI.00.EHE',
    '.ALI..EHZ'      : 'CL.ALI.00.EHZ',
    '.ALI..EHN'      : 'CL.ALI.00.EHN',
    '.ALI..EHE'      : 'CL.ALI.00.EHE',
    'crlnet.ALI..Z'  : 'CL.ALI.00.EHZ',
    'crlnet.ALI..N'  : 'CL.ALI.00.EHN',
    'crlnet.ALI..E'  : 'CL.ALI.00.EHE',
    'CL.ALI.--.EHE'  : 'CL.ALI.00.EHE',
    'CL.ALI.--.EHN'  : 'CL.ALI.00.EHN',
    'CL.ALI.--.EHZ'  : 'CL.ALI.00.EHZ',
    'CL.ALI.01.EHE'  : 'CL.ALI.00.EHE',
    'CL.ALI.01.EHN'  : 'CL.ALI.00.EHN',
    'CL.ALI.01.EHZ'  : 'CL.ALI.00.EHZ',
    'CL.ALIK.--.EHE' : 'CL.ALIK.00.EHE',
    'CL.ALIK.--.EHN' : 'CL.ALIK.00.EHN',
    'CL.ALIK.--.EHZ' : 'CL.ALIK.00.EHZ',
    'crlnet.ALIK..Z' : 'CL.ALIK.00.EHZ',
    'crlnet.ALIK..N' : 'CL.ALIK.00.EHN',
    'crlnet.ALIK..E' : 'CL.ALIK.00.EHE',
    'CL.ALIK.00.BHZ' : 'CL.ALIK.00.EHZ',
    'CL.ALIK.00.BHN' : 'CL.ALIK.00.EHN',
    'CL.ALIK.00.BHE' : 'CL.ALIK.00.EHE',
    'CL.DIM  00..E'  : 'CL.DIM.00.EHE',
    'CL.DIM  00..N'  : 'CL.DIM.00.EHN',
    'CL.DIM  00..Z'  : 'CL.DIM.00.EHZ',
    'CL.DIM.--.EHZ'  : 'CL.DIM.00.EHZ',
    'CL.DIM.--.EHN'  : 'CL.DIM.00.EHN',
    'CL.DIM.--.EHE'  : 'CL.DIM.00.EHE',
    'crlnet.DIM..Z'  : 'CL.DIM.00.EHZ',
    'crlnet.DIM..N'  : 'CL.DIM.00.EHN',
    'crlnet.DIM..E'  : 'CL.DIM.00.EHE',
    'CL.DIMT.--.EHZ' : 'CL.DIMT.00.EHZ',
    'CL.DIMT.--.EHN' : 'CL.DIMT.00.EHN',
    'CL.DIMT.--.EHE' : 'CL.DIMT.00.EHE',
    'crlnet.DIMT..Z' : 'CL.DIMT.00.EHZ',
    'crlnet.DIMT..N' : 'CL.DIMT.00.EHN',
    'crlnet.DIMT..E' : 'CL.DIMT.00.EHE',
    '.DIM..EHZ'      : 'CL.DIM.00.EHZ',
    '.DIM..EHN'      : 'CL.DIM.00.EHN',
    '.DIM..EHE'      : 'CL.DIM.00.EHE',
    'CL.DIMT.00.BHZ' : 'CL.DIMT.00.EHZ',
    'CL.DIMT.00.BHN' : 'CL.DIMT.00.EHN',
    'CL.DIMT.00.BHE' : 'CL.DIMT.00.EHE',
    'CL.KOU  00..E'  : 'CL.KOU.00.EHE',
    'CL.KOU  00..N'  : 'CL.KOU.00.EHN',
    'CL.KOU  00..Z'  : 'CL.KOU.00.EHZ',
    '.KOU..EHZ'      : 'CL.KOU.00.EHZ',
    '.KOU..EHN'      : 'CL.KOU.00.EHN',
    '.KOU..EHE'      : 'CL.KOU.00.EHE',
    'crlnet.KOU..Z'  : 'CL.KOU.00.EHZ',
    'crlnet.KOU..N'  : 'CL.KOU.00.EHN',
    'crlnet.KOU..E'  : 'CL.KOU.00.EHE',
    'CL.PAN  00..E'  : 'CL.PAN.00.EHE',
    'CL.PAN  00..N'  : 'CL.PAN.00.EHN',
    'CL.PAN  00..Z'  : 'CL.PAN.00.EHZ',
    'CL.PAN.--.EHZ'  : 'CL.PAN.00.EHZ',
    'CL.PAN.--.EHN'  : 'CL.PAN.00.EHN',
    'CL.PAN.--.EHE'  : 'CL.PAN.00.EHE',
    'crlnet.PAN..Z'  : 'CL.PAN.00.EHZ',
    'crlnet.PAN..N'  : 'CL.PAN.00.EHN',
    'crlnet.PAN..E'  : 'CL.PAN.00.EHE',
    'CL.PANR.--.EHZ' : 'CL.PANR.00.EHZ',
    'CL.PANR.--.EHN' : 'CL.PANR.00.EHN',
    'CL.PANR.--.EHE' : 'CL.PANR.00.EHE',
    'crlnet.PANR..Z' : 'CL.PANR.00.EHZ',
    'crlnet.PANR..N' : 'CL.PANR.00.EHN',
    'crlnet.PANR..E' : 'CL.PANR.00.EHE',
    'CL.PANR.00.BHZ' : 'CL.PANR.00.EHZ',
    'CL.PANR.00.BHN' : 'CL.PANR.00.EH2',
    'CL.PANR.00.BHE' : 'CL.PANR.00.EH3',
    'CL.PSA  00..E'  : 'CL.PSA.00.EHE',
    'CL.PSA  00..N'  : 'CL.PSA.00.EHN',
    'CL.PSA  00..Z'  : 'CL.PSA.00.EHZ',
    'CL.PSA.--.EHE'  : 'CL.PSA.00.EHE',
    'CL.PSA.--.EHN'  : 'CL.PSA.00.EHN',
    'CL.PSA.--.EHZ'  : 'CL.PSA.00.EHZ',
    'crlnet.PSA..Z'  : 'CL.PSA.00.EHZ',
    'crlnet.PSA..N'  : 'CL.PSA.00.EHN',
    'crlnet.PSA..E'  : 'CL.PSA.00.EHE',
    'CL.PSAR.--.EHE' : 'CL.PSAR.00.EHE',
    'CL.PSAR.--.EHN' : 'CL.PSAR.00.EHN',
    'CL.PSAR.--.EHZ' : 'CL.PSAR.00.EHZ',
    'crlnet.PSAR..Z' : 'CL.PSAR.00.EHZ',
    'crlnet.PSAR..N' : 'CL.PSAR.00.EHN',
    'crlnet.PSAR..E' : 'CL.PSAR.00.EHE',
    'CL.PSAR.00.BHZ' : 'CL.PSAR.00.EHZ',
    'CL.PSAR.00.BHN' : 'CL.PSAR.00.EHN',
    'CL.PSAR.00.BHE' : 'CL.PSAR.00.EHE',
    'HA.PSAR.00.BHZ' : 'CL.PSAR.00.EHZ',
    'HA.PSAR.00.BHN' : 'CL.PSAR.00.EHN',
    'HA.PSAR.00.BHE' : 'CL.PSAR.00.EHE',
    '.PSA..EHZ'      : 'CL.PSA.00.EHZ',
    '.PSA..EHN'      : 'CL.PSA.00.EHN',
    '.PSA..EHE'      : 'CL.PSA.00.EHE',
    'CL.PSA.01.EHE'  : 'CL.PSA.00.EHE',
    'CL.PSA.01.EHN'  : 'CL.PSA.00.EHN',
    'CL.PSA.01.EHZ'  : 'CL.PSA.00.EHZ',
    'CL.PYR  00..E'  : 'CL.PYR.00.EHE',
    'CL.PYR  00..N'  : 'CL.PYR.00.EHN',
    'CL.PYR  00..Z'  : 'CL.PYR.00.EHZ',
    'CL.PYR.--.EHE'  : 'CL.PYR.00.EHE',
    'CL.PYR.--.EHN'  : 'CL.PYR.00.EHN',
    'CL.PYR.--.EHZ'  : 'CL.PYR.00.EHZ',
    'crlnet.PYR..Z'  : 'CL.PYR.00.EHZ',
    'crlnet.PYR..N'  : 'CL.PYR.00.EHN',
    'crlnet.PYR..E'  : 'CL.PYR.00.EHE',
    'CL.PYRG.--.EHE' : 'CL.PYRG.00.EHE',
    'CL.PYRG.--.EHN' : 'CL.PYRG.00.EHN',
    'CL.PYRG.--.EHZ' : 'CL.PYRG.00.EHZ',
    'crlnet.PYRG..Z' : 'CL.PYRG.00.EHZ',
    'crlnet.PYRG..N' : 'CL.PYRG.00.EHN',
    'crlnet.PYRG..E' : 'CL.PYRG.00.EHE',
    'CL.PYRG.00.BHZ' : 'CL.PYRG.00.EHZ',
    'CL.PYRG.00.BHN' : 'CL.PYRG.00.EHN',
    'CL.PYRG.00.BHE' : 'CL.PYRG.00.EHE',
    'HA.PYRG.00.BHZ' : 'CL.PYRG.00.EHZ',
    'HA.PYRG.00.BHN' : 'CL.PYRG.00.EHN',
    'HA.PYRG.00.BHE' : 'CL.PYRG.00.EHE',
    '.PYR..EHZ'      : 'CL.PYR.00.EHZ',
    '.PYR..EHN'      : 'CL.PYR.00.EHN',
    '.PYR..EHE'      : 'CL.PYR.00.EHE',
    'CL.TEM  00..E'  : 'CL.TEM.00.EHE',
    'CL.TEM  00..N'  : 'CL.TEM.00.EHN',
    'CL.TEM  00..Z'  : 'CL.TEM.00.EHZ',
    '.TEM..EHZ'      : 'CL.TEM.00.EHE',
    '.TEM..EHN'      : 'CL.TEM.00.EHN',
    '.TEM..EHE'      : 'CL.TEM.00.EHZ',
    'crlnet.TEM..Z'  : 'CL.TEM.00.EHZ',
    'crlnet.TEM..N'  : 'CL.TEM.00.EHN',
    'crlnet.TEM..E'  : 'CL.TEM.00.EHE',
    'CL.TEME  00..E'  : 'CL.TEME.00.EHE',
    'CL.TEME  00..N'  : 'CL.TEME.00.EHN',
    'CL.TEME  00..Z'  : 'CL.TEME.00.EHZ',
    '.TEME..EHZ'      : 'CL.TEME.00.EHE',
    '.TEME..EHN'      : 'CL.TEME.00.EHN',
    '.TEME..EHE'      : 'CL.TEME.00.EHZ',
    'crlnet.TEME..Z'  : 'CL.TEME.00.EHZ',
    'crlnet.TEME..N'  : 'CL.TEME.00.EHN',
    'crlnet.TEME..E'  : 'CL.TEME.00.EHE',
    'CL.TEME.00.BHZ' : 'CL.TEME.00.EHZ',
    'CL.TEME.00.BHN' : 'CL.TEME.00.EHN',
    'CL.TEME.00.BHE' : 'CL.TEME.00.EHE',
    'CL.ROD3.--.HHE' : 'CL.ROD3.00.HHE',
    'CL.ROD3.--.HHN' : 'CL.ROD3.00.HHN',
    'CL.ROD3.--.HHZ' : 'CL.ROD3.00.HHZ',
    'crlnet.ROD3..Z' : 'CL.ROD3.00.HHZ',
    'crlnet.ROD3..N' : 'CL.ROD3.00.HHN',
    'crlnet.ROD3..E' : 'CL.ROD3.00.HHE',
    'CL.ROD3.00.BHZ' : 'CL.ROD3.00.HHZ',
    'CL.ROD3.00.BHN' : 'CL.ROD3.00.HHN',
    'CL.ROD3.00.BHE' : 'CL.ROD3.00.HHE',
    '.TRIZ..HHZ'     : 'CL.TRIZ.00.HHZ',
    '.TRIZ..HHN'     : 'CL.TRIZ.00.HHN',
    '.TRIZ..HHE'     : 'CL.TRIZ.00.HHE',
    'CL.TRIZ.--.HHZ' : 'CL.TRIZ.00.HHZ',
    'CL.TRIZ.--.HHN' : 'CL.TRIZ.00.HHN',
    'CL.TRIZ.--.HHE' : 'CL.TRIZ.00.HHE',
    'crlnet.TRIZ..Z' : 'CL.TRIZ.00.HHZ',
    'crlnet.TRIZ..N' : 'CL.TRIZ.00.HHN',
    'crlnet.TRIZ..E' : 'CL.TRIZ.00.HHE',
    'CL.TRIZ.00.BHZ' : 'CL.TRIZ.00.EHZ',
    'CL.TRIZ.00.BHN' : 'CL.TRIZ.00.EHN',
    'CL.TRIZ.00.BHE' : 'CL.TRIZ.00.EHE',
    'HA.TRIZ.00.BHZ' : 'CL.TRIZ.00.EHZ',
    'HA.TRIZ.00.BHN' : 'CL.TRIZ.00.EHN',
    'HA.TRIZ.00.BHE' : 'CL.TRIZ.00.EHE',
    'CL.ZIRI.00.HHZ' : 'CL.ZIRI.00.EHZ',
    'CL.ZIRI.00.HHN' : 'CL.ZIRI.00.EHN',
    'CL.ZIRI.00.HHE' : 'CL.ZIRI.00.EHE',
    'CL.ZIRI.--.HHZ' : 'CL.ZIRI.02.EHZ',
    'CL.ZIRI.--.HHN' : 'CL.ZIRI.02.EHN',
    'CL.ZIRI.--.HHE' : 'CL.ZIRI.02.EHE',
    'CL.ZIRI.--.EHZ' : 'CL.ZIRI.02.EHZ',
    'CL.ZIRI.--.EHN' : 'CL.ZIRI.02.EHN',
    'CL.ZIRI.--.EHE' : 'CL.ZIRI.02.EHE',
    'crlnet.ZIRI..Z' : 'CL.ZIRI.00.EHZ',
    'crlnet.ZIRI..N' : 'CL.ZIRI.00.EHN',
    'crlnet.ZIRI..E' : 'CL.ZIRI.00.EHE',
    'CL.ZIRI.00.BHZ' : 'CL.ZIRI.02.EHZ',
    'CL.ZIRI.00.BHN' : 'CL.ZIRI.02.EHN',
    'CL.ZIRI.00.BHE' : 'CL.ZIRI.02.EHE',
    'HA.ZIRI.00.BHZ' : 'CL.ZIRI.02.EHZ',
    'HA.ZIRI.00.BHN' : 'CL.ZIRI.02.EHN',
    'HA.ZIRI.00.BHE' : 'CL.ZIRI.02.EHE',
    'CL.MALA.00.BHZ' : 'CL.MALA.00.HHZ',
    'CL.MALA.00.BHN' : 'CL.MALA.00.HH2',
    'CL.MALA.00.BHE' : 'CL.MALA.00.HH3',
    '.KALI..HHZ'     : 'HA.KALE.00.HHZ',
    '.KALI..HHN'     : 'HA.KALE.00.HHN',
    '.KALI..HHE'     : 'HA.KALE.00.HHE',
    'HA.KALE.--.HHZ' : 'HA.KALE.00.HHZ',
    'HA.KALE.--.HHN' : 'HA.KALE.00.HHN',
    'HA.KALE.--.HHE' : 'HA.KALE.00.HHE',
    'HP.KALE.00.HHZ' : 'HA.KALE.00.HHZ',
    'HP.KALE.00.HHN' : 'HA.KALE.00.HHN',
    'HP.KALE.00.HHE' : 'HA.KALE.00.HHE',
    'HA.KALE.00.BHZ' : 'HA.KALE.00.HHZ',
    'HA.KALE.00.BHN' : 'HA.KALE.00.HHN',
    'HA.KALE.00.BHE' : 'HA.KALE.00.HHE',
    '.LAKK..HHZ'     : 'HA.LAKA.00.HHZ',
    '.LAKK..HHN'     : 'HA.LAKA.00.HHN',
    '.LAKK..HHE'     : 'HA.LAKA.00.HHE',
    'HA.LAKA..HHE'   : 'HA.LAKA.00.HHE',
    'HA.LAKA..HHN'   : 'HA.LAKA.00.HHN',
    'HA.LAKA..HHZ'   : 'HA.LAKA.00.HHZ',
    'HA.LAKA.00.BHE'   : 'HA.LAKA.00.HHE',
    'HA.LAKA.00.BHN'   : 'HA.LAKA.00.HHN',
    'HA.LAKA.00.BHZ'   : 'HA.LAKA.00.HHZ',
    'HA.LAKK.00.HHE' : 'HA.LAKA.00.HHE',
    'HA.LAKK.00.HHN' : 'HA.LAKA.00.HHN',
    'HA.LAKK.00.HHZ' : 'HA.LAKA.00.HHZ',
    '.SERG..HHE'     : 'HP.SERG.00.HHE',
    '.SERG..HHN'     : 'HP.SERG.00.HHN',
    '.SERG..HHZ'     : 'HP.SERG.00.HHZ',
    'HP.SERG..HHZ'   : 'HP.SERG.00.HHZ',
    'HP.SERG..HHN'   : 'HP.SERG.00.HHN',
    'HP.SERG..HHE'   : 'HP.SERG.00.HHE',
    'HP.SERG.--.HHZ' : 'HP.SERG.00.HHZ',
    'HP.SERG.--.HHN' : 'HP.SERG.00.HHN',
    'HP.SERG.--.HHE' : 'HP.SERG.00.HHE',
    'HP.SERG.00.BHZ' : 'HP.SERG.00.HHZ',
    'HP.SERG.00.BHN' : 'HP.SERG.00.HHN',
    'HP.SERG.00.BHE' : 'HP.SERG.00.HHE',
    'HP.ANX..HHZ'    : 'HP.ANX.00.HHZ',
    'HP.ANX..HHN'    : 'HP.ANX.00.HHN',
    'HP.ANX..HHE'    : 'HP.ANX.00.HHE',
    'HP.ANX.--.HHZ'  : 'HP.ANX.00.HHZ',
    'HP.ANX.--.HHN'  : 'HP.ANX.00.HHN',
    'HP.ANX.--.HHE'  : 'HP.ANX.00.HHE',
    'HP.ANX.00.BHZ'  : 'HP.ANX.00.HHZ',
    'HP.ANX.00.BHN'  : 'HP.ANX.00.HHN',
    'HP.ANX.00.BHE'  : 'HP.ANX.00.HHE',
    'HP.EFP.--.HHZ'  : 'HP.EFP.00.HHZ',
    'HP.EFP.--.HHN'  : 'HP.EFP.00.HHN',
    'HP.EFP.--.HHE'  : 'HP.EFP.00.HHE',
    'HP.EFP..EHZ'    : 'HP.EFP.00.HHZ',
    'HP.EFP..EHN'    : 'HP.EFP.00.HHN',
    'HP.EFP..EHE'    : 'HP.EFP.00.HHE',
    'HP.EFP.--.EHZ'  : 'HP.EFP.00.HHZ',
    'HP.EFP.--.EHN'  : 'HP.EFP.00.HHN',
    'HP.EFP.--.EHE'  : 'HP.EFP.00.HHE',
    'HP.EFP.00.BHZ'  : 'HP.EFP.00.HHZ',
    'HP.EFP.00.BHN'  : 'HP.EFP.00.HHN',
    'HP.EFP.00.BHE'  : 'HP.EFP.00.HHE',
    'HP.VVK.--.BHZ'  : 'HP.VVK.00.EHZ',
    'HP.VVK.--.BHN'  : 'HP.VVK.00.EHN',
    'HP.VVK.--.BHE'  : 'HP.VVK.00.EHE',
    'HP.VVK.00.BHZ'  : 'HP.VVK.00.EHZ',
    'HP.VVK.00.BHN'  : 'HP.VVK.00.EHN',
    'HP.VVK.00.BHE'  : 'HP.VVK.00.EHE',
    'HP.UPR.00.BHZ'  : 'HP.UPR.00.EHZ',
    'HP.UPR.00.BHN'  : 'HP.UPR.00.EHN',
    'HP.UPR.00.BHE'  : 'HP.UPR.00.EHE'
}
